#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$bin = __DIR__ . '/vendor/bin/flo';
$php = PHP_BINARY;

$args = array_slice($argv, 1);
$cmd = escapeshellarg($php) . ' ' . escapeshellarg($bin);
if ($args) {
    $cmd .= ' ' . implode(' ', array_map('escapeshellarg', $args));
}

passthru($cmd, $exitCode);
exit($exitCode);